### ISSUE TITLE
Instructions for installation and starting GAP

### ISSUE THREAD

**Issue by angeldelriomateos** [gap-system/GapWWW#261] opened 2021-11-14 18:19 UTC
I use GAP to teach and every course I encounter complains from the students which claims that the instructions for installing and running GAP in the webpage are obscure and cumbersome. I believe that they are right. After several attempts I have not be able to get the program installed on several Apple computers of the students. 
Moreover, there is not instructions on how start GAP. 

In my opinion the webpage should contain friendly and simple instructions clearly displayed in the main page of installation.

**Comment by fingolfin** [comment] 2021-11-14 18:28
Sure. Agreed!

Duplicate of issue #16, i.e. this is long known. Just nobody has been willing to volunteer working on this further yet. Actually  the whole website needs a major overhaul.

Contributions highly welcome!

**Closed by fingolfin** 2021-11-14 18:28 UTC

**Comment by alex-konovalov** [comment] 2021-11-14 19:15
@angeldelriomateos thanks - I've also updated installation instructions at https://github.com/gap-system/homebrew-gap to explain that `gap` starts GAP if it was installed with homebrew.
